apiVersion: v1
kind: Service
metadata:
  name: hmrs-backend-service
  namespace: hmrs
spec:
  type: NodePort
  selector:
    app: hmrs-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080